[package]
name = "balcony"
version = "0.1.0"
edition = "2021"

authors = "Keith Wright"
description = "An example of organizing rust code based on what is on my balcony."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
